In [2]:
import pandas as pd
import numpy as np
# explicitly require this experimental feature
from sklearn.experimental import enable_iterative_imputer  # noqa
# now you can import normally from sklearn.impute
from sklearn.impute import IterativeImputer
from sklearn.ensemble import ExtraTreesRegressor
from sklearn.linear_model import BayesianRidge
import random

In [20]:

data = np.random.random([1000,20])
data

array([[0.13759118, 0.26405712, 0.22819585, ..., 0.43042273, 0.30799435,
        0.26187024],
       [0.48730237, 0.13104671, 0.62235968, ..., 0.5924    , 0.54451184,
        0.88435505],
       [0.54430918, 0.16859229, 0.76376755, ..., 0.51929303, 0.06241532,
        0.05419505],
       ...,
       [0.90055732, 0.10813659, 0.98993452, ..., 0.5476304 , 0.60847316,
        0.57071051],
       [0.8130049 , 0.36418512, 0.93565155, ..., 0.05273742, 0.34137124,
        0.19696307],
       [0.5666985 , 0.88981366, 0.64041033, ..., 0.72373866, 0.98807172,
        0.11174661]])

In [21]:
null_data = np.empty([1000,2])
null_data[:] = np.nan

In [22]:
null_data

array([[nan, nan],
       [nan, nan],
       [nan, nan],
       ...,
       [nan, nan],
       [nan, nan],
       [nan, nan]])

In [23]:
full_data = np.concatenate((data,null_data), axis=1)

In [24]:
full_data

array([[0.13759118, 0.26405712, 0.22819585, ..., 0.26187024,        nan,
               nan],
       [0.48730237, 0.13104671, 0.62235968, ..., 0.88435505,        nan,
               nan],
       [0.54430918, 0.16859229, 0.76376755, ..., 0.05419505,        nan,
               nan],
       ...,
       [0.90055732, 0.10813659, 0.98993452, ..., 0.57071051,        nan,
               nan],
       [0.8130049 , 0.36418512, 0.93565155, ..., 0.19696307,        nan,
               nan],
       [0.5666985 , 0.88981366, 0.64041033, ..., 0.11174661,        nan,
               nan]])

In [39]:
full_data = np.random.permutation(full_data.flat)

In [45]:
full_data = full_data.reshape([1000,22])

In [46]:
np.isnan(full_data)

array([[False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       ...,
       [False, False,  True, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False]])

In [47]:
imputer = IterativeImputer(BayesianRidge())
impute_data = pd.DataFrame(imputer.fit_transform(full_data))

In [48]:
impute_data.head()

0         1         2         3         4         5         6  \
0  0.214650  0.552840  0.677496  0.802689  0.560499  0.064161  0.592907   
1  0.508101  0.978570  0.195610  0.774654  0.903958  0.421433  0.331976   
2  0.028865  0.426927  0.218849  0.431628  0.538252  0.116217  0.546143   
3  0.338452  0.747651  0.220309  0.484886  0.725487  0.103777  0.257080   
4  0.597271  0.554859  0.406642  0.753356  0.827632  0.351636  0.980669   

          7         8         9        10        11        12        13  \
0  0.590266  0.482800  0.752964  0.713785  0.520790  0.161941  0.907412   
1  0.492004  0.302908  0.415978  0.173914  0.229168  0.878433  0.133105   
2  0.992728  0.368956  0.093879  0.502808  0.826442  0.490191  0.798532   
3  0.496492  0.484115  0.735550  0.597735  0.490736  0.648025  0.487448   
4  0.448356  0.251475  0.117031  0.669014  0.506988  0.283237  0.395910   

         14        15        16        17        18        19        20  \
0  0.360499  0.606902  0.427781  0.713413  0.478560  0.604829  0.180835   
1  0.195051  0.076413  0.222467  0.282834  0.896853  0.181189  0.501477   
2  0.479049  0.181216  0.462503  0.859003  0.441767  0.481791  0.912649   
3  0.342347  0.435213  0.069986  0.192963  0.679379  0.489536  0.869426   
4  0.394320  0.154492  0.508196  0.441378  0.813738  0.108033  0.582706   

         21  
0  0.304343  
1  0.693260  
2  0.654312  
3  0.520066  
4  0.763211

In [49]:
impute_data.isnull()

0      1      2      3      4      5      6      7      8      9  \
0    False  False  False  False  False  False  False  False  False  False   
1    False  False  False  False  False  False  False  False  False  False   
2    False  False  False  False  False  False  False  False  False  False   
3    False  False  False  False  False  False  False  False  False  False   
4    False  False  False  False  False  False  False  False  False  False   
..     ...    ...    ...    ...    ...    ...    ...    ...    ...    ...   
995  False  False  False  False  False  False  False  False  False  False   
996  False  False  False  False  False  False  False  False  False  False   
997  False  False  False  False  False  False  False  False  False  False   
998  False  False  False  False  False  False  False  False  False  False   
999  False  False  False  False  False  False  False  False  False  False   

        10     11     12     13     14     15     16     17     18     19  \
0    False  False  False  False  False  False  False  False  False  False   
1    False  False  False  False  False  False  False  False  False  False   
2    False  False  False  False  False  False  False  False  False  False   
3    False  False  False  False  False  False  False  False  False  False   
4    False  False  False  False  False  False  False  False  False  False   
..     ...    ...    ...    ...    ...    ...    ...    ...    ...    ...   
995  False  False  False  False  False  False  False  False  False  False   
996  False  False  False  False  False  False  False  False  False  False   
997  False  False  False  False  False  False  False  False  False  False   
998  False  False  False  False  False  False  False  False  False  False   
999  False  False  False  False  False  False  False  False  False  False   

        20     21  
0    False  False  
1    False  False  
2    False  False  
3    False  False  
4    False  False  
..     ...    ...  
995  False  False  
996  False  False  
997  False  False  
998  False  False  
999  False  False  

[1000 rows x 22 columns]